version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  milvus-standalone:
    image: milvusdb/milvus:v2.3.3
    ports:
      - "19530:19530"
      - "9091:9091"

  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    environment:
      MILVUS_HOST: milvus-standalone
      MILVUS_PORT: 19530
    depends_on:
      - kafka
      - milvus-standalone
    ports:
      - "8000:8000"

  tracker:
    build: .
    command: python tracker/reid.py --live
    depends_on:
      - kafka

  dashboard:
    build: .
    command: uvicorn dashboard.app:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    depends_on:
      - api
